name:                sf-signer
version:             0.2.0
github:              "syncom/sf-signer"
license:             BSD3
author:              "Ning Shang"
maintainer:          "syncom.dev@gmail.com"
copyright:           "2022 Ning Shang"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/syncom/sf-signer#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- cryptonite
- bytestring
- text

library:
  source-dirs: src
  exposed-modules:
  - SignerLib
  - CliLib
  dependencies:
  - foldl
  - HsOpenSSL

# Pro-tip from https://stackoverflow.com/questions/65013554/force-static-compilation-in-stack
_buildopt: !include ./build-options.yaml

executables:
  sfsigner:
    main:                Main.hs
    source-dirs:         app
    <<: *build_options
    dependencies:
    - sf-signer

tests:
  sf-signer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sf-signer
    - QuickCheck
    - foldl
