name:                sf-signer
version:             0.0.0
github:              "syncom/sf-signer"
license:             BSD3
author:              "Ning Shang"
maintainer:          "syncom.dev@gmail.com"
copyright:           "2022 Ning Shang"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/syncom/sf-signer#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- cryptonite
- bytestring
- text

library:
  source-dirs: src
  exposed-modules:
  - SignerLib
  - CliLib
  dependencies:
  - foldl
  - HsOpenSSL

executables:
  sfsigner:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -static
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # "" to me removed by tools. Do not edit
    ###START STATIC LINKING###
    cc-options:
    - -static
    ld-options:
    - -static
    - -pthread
    # cf https://github.com/icfpcontest2020/starterkit-haskell/issues/2#issuecomment-774894327
    - -fuse-ld=bfd
    ###END STATIC LINKING###
    dependencies:
    - sf-signer

tests:
  sf-signer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sf-signer
    - QuickCheck
    - foldl
