on:
  push:
    tags:
      - 'v*'
name: "Release Deployable"
jobs:
  release-squbi:
    name: "Release sfsigner"
    runs-on: ${{ matrix.os }}
    environment: "release"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Install dependencies
        run: |
          set -euxo pipefail
          if [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
            sudo apt-get update
          fi
          sudo curl -sSL https://get.haskellstack.org/ | sh -s - -f
          stack --version
          if [ ${{ matrix.os }} = 'macos-latest' ]; then
            # for `sha256sum`
            brew install coreutils
          fi

      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0

      - name: Set env
        run: |
          set -euxo pipefail
          # set RELEASE_VERSION as tag version
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "OS=$(echo $(uname -s) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Download and validate sfsigner v0.0.0
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}
          mkdir -p dogfood
          SFSIGNER0_URL="https://github.com/syncom/sf-signer/releases/download/v0.0.0/sfsigner-${OS}-${ARCH}"
          SFSIGNER0_EXE="dogfood/sfsigner0"
          echo "SFSIGNER0_EXE=${{ github.workspace }}/dogfood/sfsigner0" >> $GITHUB_ENV
          curl -L "${SFSIGNER0_URL}" -o "${SFSIGNER0_EXE}"
          # linux-x86_64
          EXPECTED_SUM1="7cfd5c00b8bc7215bc99972017da1837c514856db6d72b8e44e9136cb4fe9050"
          # darwin-x86_64
          EXPECTED_SUM2="3e8692fa751983b75b11392968b6244e48b8b56a3363257286840ac35a696c06"
          CHECKSUM="$(sha256sum "${SFSIGNER0_EXE}" | cut -f1 -d' ')"
          [ "$CHECKSUM" = "$EXPECTED_SUM1" ] || [ "$CHECKSUM" = "$EXPECTED_SUM2" ] || exit 1
          chmod +x "${SFSIGNER0_EXE}"
          "${SFSIGNER0_EXE}" version

      - name: Build at tagged revision
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}
          git checkout tags/v"${RELEASE_VERSION}" -b v"${RELEASE_VERSION}"
          # Linking statically for Linux, dynamically otherwise
          if [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
            make static-build
          else
            make build
          fi
          mv build/sfsigner build/sfsigner-"$OS"-"$ARCH"

      - name: Sign artifact using sfsigner v0.0.0
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}
          EXE="build/sfsigner-${OS}-${ARCH}"
          "${SFSIGNER0_EXE}" sign -c data/certs/sfsigner.pem \
            -o "${EXE}.sig" "${EXE}"
          # Self-check: verify signature
          "${SFSIGNER0_EXE}" verify -p "${EXE}" -s "${EXE}.sig" \
            -c data/certs/sfsigner.pem -t data/ca.pem

        env:
          SFSIGNER_PRIVATE_KEY: ${{ secrets.SFSIGNER_PRIVATE_KEY }}

      - name: Ensure app version matches tag version
        run: |
          set -euxo pipefail
          APP_VERSION="$(build/sfsigner-"$OS"-"$ARCH" version)"
          if [ "$APP_VERSION" != "$RELEASE_VERSION" ]; then
            echo "version (${APP_VERSION}) in package.yaml and tagged version (${RELEASE_VERSION}) mismatch"
            exit 1
          fi

      - name: "Release versioned"
        # v1.10.0
        uses: ncipollo/release-action@58ae73b360456532aafd58ee170c045abbeaee37
        with:
          allowUpdates: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
