name: "Sanity Checks"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sanity-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0
      - name: Install stack etc
        run: |
          if [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
            sudo apt-get update
            sudo apt-get install -y faketime
          fi
          sudo curl -sSL https://get.haskellstack.org/ | sh -s - -f
          stack --version
          if [ ${{ matrix.os }} = 'macos-latest' ]; then
            # for `sha256sum`
            brew install coreutils
            brew install libfaketime
          fi
      - name: Build
        run: |
          cd ${{ github.workspace }}
          # Linking statically for Linux, dynamically otherwise
          if [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
            make static-build
          else
            make build
          fi
          file build/sfsigner
      - name: Unit test
        run: |
          make test
      - name: Integration test
        run: |
          ./script/sign-and-verify.sh
