name: "Sanity Checks"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sanity-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        # v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0
      - name: Install stack etc
        run: |
          if [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
            sudo apt update
            sudo apt install -y faketime
          fi
          sudo curl -sSL https://get.haskellstack.org/ | sh -s - -f
          stack --version
          if [ ${{ matrix.os }} = 'macos-latest' ]; then
            # for `sha256sum`
            brew install coreutils
            brew install libfaketime
            brew install openssl@3
            echo "STACK_EXTRA_FLAGS=--extra-include-dirs=$(brew --prefix openssl@3)/include --extra-lib-dirs=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV
            echo "LDFLAGS=-L$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
            echo "CPPFLAGS=-I$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          fi
      - name: Build
        run: |
          cd ${{ github.workspace }}
          # Link dynamically; static linking is a pain, and leave it out for now
          make build
          file build/sfsigner
      - name: Unit test
        run: |
          make test
      - name: Integration test
        run: |
          ./script/sign-and-verify.sh
