name: "Sanity Check for Static Build with Nix"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sanity-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        # v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 2
      - name: "Static Build with Nix"
        run: |
          cd ${{ github.workspace }}/r10e-static-build
          make sfsigner-r10e
